image: golang:1.10
stages:
  - build
  - test

before_script:
  - go get -u github.com/golang/dep/cmd/dep
  - mkdir -p /go/src/gitlab.com/yakshaving.art
  - cp -r /builds/yakshaving.art/git-pull-mirror /go/src/gitlab.com/yakshaving.art/
  - cd /go/src/gitlab.com/yakshaving.art/git-pull-mirror
  - dep ensure

build:
  stage: build
  script:
    - go build

test:
  stage: test
  coverage: '/^coverage:\s+(\d+.\d+)%\s+of statements$/'
  script:
    - go test -v -cover ./...

